# Generated by Django 2.1.7 on 2019-03-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
