# Generated by Django 2.1.7 on 2019-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('Phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=6)),
            ],
        ),
    ]
